packages:
  - 'tools/workspace-plugin'

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: true
  unrs-resolver: false

autoInstallPeers: true
minimumReleaseAgeExclude:
  - '@iconify/json@2.2.515 || 2.2.516 || 2.2.517 || 2.2.518 || 2.2.519'
strictPeerDependencies: false
