packages:
  - docs
  - packages/*
catalogs:
  angular:
    '@angular/core': ^19.2.6
    ng-packagr: ^19.2.2
    tslib: ^2.3.0
  dev:
    '@antfu/eslint-config': ^4.12.0
    '@antfu/ni': ^24.3.0
    '@antfu/nip': ^0.1.0
    '@iconify/json': latest
    '@iconify/types': ^2.0.0
    '@iconify/utils': ^2.3.0
    '@types/cli-progress': ^3.11.6
    '@types/ejs': ^3.1.5
    '@types/node': ^22.14.1
    bumpp: ^10.1.0
    cheerio: ^1.0.0
    cli-progress: ^3.12.0
    ejs: ^3.1.10
    eslint: ^9.24.0
    execa: ^9.5.2
    lint-staged: ^15.5.1
    p-limit: ^6.2.0
    picocolors: ^1.1.1
    pnpm: ^10.8.0
    simple-git-hooks: ^2.12.1
    tsx: ^4.19.3
    typescript: ^5.7.3
  vite:
    vite: ^6.3.0
    vitest: ^3.1.1
