packages:
  - docs
  - packages/*
catalogs:
  angular:
    '@angular/compiler-cli': ^19.2.9
    '@angular/core': ^19.2.6
    ng-packagr: ^19.2.2
    tslib: ^2.3.0
  cli:
    '@antfu/eslint-config': ^4.12.0
    '@antfu/ni': ^24.3.0
    '@antfu/nip': ^0.1.0
    bumpp: ^10.1.0
    esbuild: ^0.25.4
    eslint: ^9.24.0
    lint-staged: ^15.5.1
    simple-git-hooks: ^2.12.1
    tsx: ^4.19.3
    typescript: ^5.7.3
    vite: ^6.3.0
  testing:
    vitest: ^3.1.1
  types:
    '@types/cli-progress': ^3.11.6
    '@types/ejs': ^3.1.5
    '@types/node': ^22.14.1
  utils:
    '@iconify/json': ^2.2.335
    '@iconify/types': ^2.0.0
    '@iconify/utils': ^2.3.0
    cheerio: ^1.0.0
    cli-progress: ^3.12.0
    ejs: ^3.1.10
    p-limit: ^6.2.0
    picocolors: ^1.1.1
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - simple-git-hooks
