name: Generate icons

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm exec nx run @ngxi/source:update-icons-set

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_GITHUB }}
          commit-message: 'feat: update icons-set'
          title: 'feat: update icons-set'
          body: This PR updates the icons-set
          branch: update-icons-set
          base: main
          delete-branch: true
          committer: Adrián UB <22903142+adrian-ub@users.noreply.github.com>
          author: Adrián UB <22903142+adrian-ub@users.noreply.github.com>
