name: Generate icons

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB }}

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm exec nx run @ngxi/source:update-icons-set

      - name: Check if there are changes
        id: git-check
        run: |
          git config --global user.name 'Adrián UB'
          git config --global user.email '22903142+adrian-ub@users.noreply.github.com'

          git add -A
          if ! git diff --cached --quiet; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git commit -m "feat: update icons-set"
          git push

      - name: Bump version
        if: steps.git-check.outputs.has_changes == 'true'
        run: pnpm bumpp next -y
